### ISSUE TITLE
fedora 24 install problems

### ISSUE THREAD

**Issue by WillyWinkel** [Gjum/pyAgar.io#17]
Hey,

followed the instructions and installed by `sudo pip install gagar` then running I had the following problem:

```
> gagar -h
Traceback (most recent call last):
  File "/usr/bin/gagar", line 9, in <module>
    load_entry_point('gagar==0.1.1', 'gui_scripts', 'gagar')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 568, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2720, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2380, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2386, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/gagar/main.py", line 181
    def __init__(self, key, *subs, disabled=False):
                                          ^
SyntaxError: invalid syntax
```

nice idea btw

**Comment by Gjum** [comment]
@WillyWinkel Try pip3 instead of pip, looks like a python2 issue.

**Comment by WillyWinkel** [comment]
dont know why yet, but I cant use pip3

**Comment by Gjum** [comment]
You need python 3 for this project. Fedora instructions: http://superuser.com/questions/941418/run-pip-for-python3-on-fedora
It should also not be very difficult to port it to python 2 if you like to do that.
